on:
  push:
    branches:
    - main
    - release/*
jobs:
 visualize:
   runs-on: ubuntu-latest
   steps:
   - name: Get wordcount
     shell: bash
     run: wc -l helloworld.js > /tmp/linesofcode.txt
   - name: Send email
     uses: devellany/send-mailer@v1.0.2
     with:
      host: smtp.google.com
      account: ${{secrets.ACCOUNT}}
      password: ${{secrets.MAIL_PASSWORD}}
      sender: devellany
      from: ${{secrets.MAIL_ADDRESS}}
      to: devellay@dico.me
      subject: Lineofcode
      body: Lineofcode
      attachments: file://tmp/linesofcode.txt
